background_opacity 1
font_size 10
background #0F1011             
# #111111 0.7
window_padding_width 15
bold_font none
cursor_blink_interval 0
cursor_trail 200
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 2
font_family Ubuntu
