
# middle config
echo t.bold fg.yellow getUsername fg.black "@" fg.yellow getHostname
echo fg.blue "Distro: " fg.white t.bold getOsName
echo fg.blue "Platform: " fg.white t.bold getPlatform"
echo fg.blue "Kernel: " fg.white t.bold getKernel
echo fg.blue "Memory: " fg.white t.bold getMemory
echo fg.blue "CPU: " fg.white t.bold getCpu
echo fg.blue "GPU: " fg.white t.bold getGpu
echo fg.blue "Packages: " fg.white t.bold getPackages
echo fg.blue "Disk: " fg.white t.bold getDisk(/)
echo fg.blue "Desktop: " fg.white t.bold getDesktop
echo fg.blue "Primary: " fg.white t.bold getMonitor(0)
echo fg.blue "Uptime: " fg.white t.bold getUptime
echo fg.blue "Shell: " fg.white t.bold getShell

ascii = "/home/lynch/.config/ffetch/JTG.txt"
ascii_color = "fg.cyan"
